"""Changing quantity_per_serving to quantity in recipe_ingredient

Revision ID: 014ae6ed70d8
Revises: 36d27e8bb216
Create Date: 2026-07-13 15:28:34.163359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014ae6ed70d8'
down_revision: Union[str, Sequence[str], None] = '36d27e8bb216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe_ingredient",
        "quantity_per_serving",
        new_column_name="quantity"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "recipe_ingredient",
        "quantity",
        new_column_name="quantity_per_serving"
    )
    # ### end Alembic commands ###
