"""Adding a deciamal place for quantity attributes

Revision ID: 062e466e90cc
Revises: c23b83d33748
Create Date: 2026-09-06 19:18:28.697090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062e466e90cc'
down_revision: Union[str, Sequence[str], None] = 'c23b83d33748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_stock', 'quantity',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.DECIMAL(precision=16, scale=3),
               existing_nullable=False)
    op.alter_column('item_to_buy', 'units_to_buy',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.DECIMAL(precision=16, scale=3),
               existing_nullable=False)
    op.alter_column('meal_ingredient', 'quantity',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.DECIMAL(precision=16, scale=3),
               existing_nullable=False)
    op.alter_column('recipe_ingredient', 'quantity',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.DECIMAL(precision=16, scale=3),
               existing_nullable=False)
    op.alter_column('shopping_item', 'units_bought',
               existing_type=sa.NUMERIC(precision=16, scale=2),
               type_=sa.DECIMAL(precision=16, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_item', 'unit_price',
               existing_type=sa.DECIMAL(precision=16, scale=3),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('recipe_ingredient', 'quantity',
               existing_type=sa.DECIMAL(precision=16, scale=3),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('meal_ingredient', 'quantity',
               existing_type=sa.DECIMAL(precision=16, scale=3),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('item_to_buy', 'units_to_buy',
               existing_type=sa.DECIMAL(precision=16, scale=3),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('ingredient_stock', 'quantity',
               existing_type=sa.DECIMAL(precision=16, scale=3),
               type_=sa.NUMERIC(precision=16, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
