"""Adding code to item category for identification

Revision ID: 273243c55d5f
Revises: b9abfd08215d
Create Date: 2026-08-04 20:35:32.165588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273243c55d5f'
down_revision: Union[str, Sequence[str], None] = 'b9abfd08215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_category', sa.Column('code', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'item_category', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_category', type_='unique')
    op.drop_column('item_category', 'code')
    # ### end Alembic commands ###
