"""Adding nb_serving attribute to PlanningRecipe

Revision ID: 29e2da8dfa09
Revises: 792c7e6c800c
Create Date: 2026-06-26 19:35:39.702394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e2da8dfa09'
down_revision: Union[str, Sequence[str], None] = '792c7e6c800c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_recipe', sa.Column('nb_serving', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_recipe', 'nb_serving')
    # ### end Alembic commands ###
