"""Adding description to planning recipe

Revision ID: 36d27e8bb216
Revises: 29e2da8dfa09
Create Date: 2026-06-29 10:53:40.387538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d27e8bb216'
down_revision: Union[str, Sequence[str], None] = '29e2da8dfa09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planning_recipe', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planning_recipe', 'description')
    # ### end Alembic commands ###
