"""Ref household in app user

Revision ID: 383e3015dd37
Revises: 8845e8714fd6
Create Date: 2026-05-12 15:56:06.580579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383e3015dd37'
down_revision: Union[str, Sequence[str], None] = '8845e8714fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('ref_household_id', sa.String(length=64), nullable=False))
    op.create_foreign_key(None, 'app_user', 'household', ['ref_household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='foreignkey')
    op.drop_column('app_user', 'ref_household_id')
    # ### end Alembic commands ###
