"""Adding ItemToBuy model

Revision ID: 4f0a37e3de68
Revises: ec1e781f23d5
Create Date: 2026-07-18 23:01:03.789938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0a37e3de68'
down_revision: Union[str, Sequence[str], None] = 'ec1e781f23d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_to_buy',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_ingredient_id', sa.String(length=64), nullable=True),
    sa.Column('ref_item_category_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['ref_item_category_id'], ['item_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('shopping_item', sa.Column('unit_price', sa.DECIMAL(precision=16, scale=2), nullable=False))
    op.add_column('shopping_item', sa.Column('units_bought', sa.Integer(), nullable=False))
    op.add_column('shopping_item', sa.Column('ref_ingredient_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'shopping_item', 'ingredient', ['ref_ingredient_id'], ['id'])
    op.drop_column('shopping_item', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_item', sa.Column('price', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shopping_item', type_='foreignkey')
    op.drop_column('shopping_item', 'ref_ingredient_id')
    op.drop_column('shopping_item', 'units_bought')
    op.drop_column('shopping_item', 'unit_price')
    op.drop_table('item_to_buy')
    # ### end Alembic commands ###
