"""Images in recipes and ingredients

Revision ID: 526339f10605
Revises: a939697aff43
Create Date: 2026-05-25 18:55:31.910648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526339f10605'
down_revision: Union[str, Sequence[str], None] = 'a939697aff43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('ingredient', sa.Column('storage_key', sa.String(length=255), nullable=True))
    op.add_column('recipe', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('recipe', sa.Column('storage_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'storage_key')
    op.drop_column('recipe', 'image_url')
    op.drop_column('ingredient', 'storage_key')
    op.drop_column('ingredient', 'image_url')
    # ### end Alembic commands ###
