"""delete unit attribute from ingredient

Revision ID: 5f7cd46464c7
Revises: d97c3758f282
Create Date: 2026-06-16 18:55:00.812679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7cd46464c7'
down_revision: Union[str, Sequence[str], None] = 'd97c3758f282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'unit')
    op.add_column('meal_ingredient', sa.Column('ingredient_unit', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_ingredient', 'ingredient_unit')
    op.add_column('ingredient', sa.Column('unit', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
