"""Removing unique from name of item_to_buy and shopping_item

Revision ID: 78319d6058a4
Revises: 6265d1269461
Create Date: 2026-07-23 17:49:10.504801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78319d6058a4'
down_revision: Union[str, Sequence[str], None] = '6265d1269461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_to_buy_name_key'), 'item_to_buy', type_='unique')
    op.drop_constraint(op.f('shopping_item_name_key'), 'shopping_item', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('shopping_item_name_key'), 'shopping_item', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('item_to_buy_name_key'), 'item_to_buy', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
