"""Adding ingredientUnit id as foreign key for meal ingredient

Revision ID: 792c7e6c800c
Revises: fe8f8c4507fb
Create Date: 2026-06-19 18:58:15.539145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792c7e6c800c'
down_revision: Union[str, Sequence[str], None] = 'fe8f8c4507fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_ingredient', sa.Column('ref_ingredient_unit_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'meal_ingredient', 'ingredient_unit', ['ref_ingredient_unit_id'], ['id'])
    op.drop_column('meal_ingredient', 'ingredient_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_ingredient', sa.Column('ingredient_unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meal_ingredient', type_='foreignkey')
    op.drop_column('meal_ingredient', 'ref_ingredient_unit_id')
    # ### end Alembic commands ###
