"""CHange password_hash field of app_user to just password

Revision ID: a939697aff43
Revises: 383e3015dd37
Create Date: 2026-05-12 16:21:28.025231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a939697aff43'
down_revision: Union[str, Sequence[str], None] = '383e3015dd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('password', sa.Text(), nullable=False))
    op.drop_column('app_user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('app_user', 'password')
    # ### end Alembic commands ###
