"""Making units_bought and units_to_buy Deimal instead of int

Revision ID: a9a881deef4d
Revises: 38956d7d32fc
Create Date: 2026-08-15 18:59:15.090872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a881deef4d'
down_revision: Union[str, Sequence[str], None] = '38956d7d32fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
