"""First generation

Revision ID: ad90b3fe5cb3
Revises: 
Create Date: 2026-05-12 14:31:21.160862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90b3fe5cb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_endpoint',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('path_name', sa.String(length=64), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_name', 'method', name='uix_path_name_method')
    )
    op.create_table('app_user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('default_language', sa.String(length=3), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('household',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_type',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_parent_role_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['ref_parent_role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('seller',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('endpoint_access',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_role_id', sa.String(length=64), nullable=False),
    sa.Column('ref_api_endpoint_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_api_endpoint_id'], ['api_endpoint.id'], ),
    sa.ForeignKeyConstraint(['ref_role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('ref_role_id', 'ref_api_endpoint_id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('estimated_price', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_ingredient_type_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_ingredient_type_id'], ['ingredient_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('parallel_cooking', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_household_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=16), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('user_role',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_role_id', sa.String(length=64), nullable=False),
    sa.Column('ref_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['ref_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('ref_role_id', 'ref_user_id')
    )
    op.create_table('ingredient_stock',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_ingredient_id', sa.String(length=64), nullable=False),
    sa.Column('ref_seller_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['ref_seller_id'], ['seller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nb_serving', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_recipe_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_recipe',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('planning_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_household_id', sa.String(length=64), nullable=False),
    sa.Column('ref_recipe_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['ref_recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredient',
    sa.Column('quantity_per_serving', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('insertion_id', sa.String(length=64), nullable=False),
    sa.Column('ref_recipe_id', sa.String(length=64), nullable=False),
    sa.Column('ref_ingredient_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['ref_recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('insertion_id', 'ref_recipe_id', 'ref_ingredient_id')
    )
    op.create_table('meal_ingredient',
    sa.Column('quantity', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_meal_id', sa.String(length=64), nullable=False),
    sa.Column('ref_ingredient_stock_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_ingredient_stock_id'], ['ingredient_stock.id'], ),
    sa.ForeignKeyConstraint(['ref_meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('ref_meal_id', 'ref_ingredient_stock_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_ingredient')
    op.drop_table('recipe_ingredient')
    op.drop_table('planning_recipe')
    op.drop_table('meal')
    op.drop_table('ingredient_stock')
    op.drop_table('user_role')
    op.drop_table('refresh_tokens')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    op.drop_table('endpoint_access')
    op.drop_table('state')
    op.drop_table('seller')
    op.drop_table('role')
    op.drop_table('ingredient_type')
    op.drop_table('household')
    op.drop_table('app_user')
    op.drop_table('api_endpoint')
    # ### end Alembic commands ###
