"""Adding a ref to shopping_item_id in item_to_buy

Revision ID: b1cbc7581009
Revises: 78319d6058a4
Create Date: 2026-07-23 18:11:55.110086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cbc7581009'
down_revision: Union[str, Sequence[str], None] = '78319d6058a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_to_buy', sa.Column('ref_shopping_item_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'item_to_buy', 'shopping_item', ['ref_shopping_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_to_buy', type_='foreignkey')
    op.drop_column('item_to_buy', 'ref_shopping_item_id')
    # ### end Alembic commands ###
