"""Adding units_to_buy and estimated_unit_price on ItemToBuy

Revision ID: b9abfd08215d
Revises: b1cbc7581009
Create Date: 2026-07-31 13:40:51.486462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9abfd08215d'
down_revision: Union[str, Sequence[str], None] = 'b1cbc7581009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_stock', sa.Column('ref_household_id', sa.String(length=64), nullable=False))
    op.create_foreign_key(None, 'ingredient_stock', 'household', ['ref_household_id'], ['id'])
    op.add_column('item_to_buy', sa.Column('estimated_unit_price', sa.DECIMAL(precision=16, scale=2), nullable=False))
    op.add_column('item_to_buy', sa.Column('units_to_buy', sa.Integer(), nullable=False))
    op.add_column('item_to_buy', sa.Column('ref_household_id', sa.String(length=64), nullable=False))
    op.create_foreign_key(None, 'item_to_buy', 'household', ['ref_household_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_to_buy', type_='foreignkey')
    op.drop_column('item_to_buy', 'ref_household_id')
    op.drop_column('item_to_buy', 'units_to_buy')
    op.drop_column('item_to_buy', 'estimated_unit_price')
    op.drop_constraint(None, 'ingredient_stock', type_='foreignkey')
    op.drop_column('ingredient_stock', 'ref_household_id')
    # ### end Alembic commands ###
