"""Making units_bought and units_to_buy Deimal instead of int

Revision ID: c23b83d33748
Revises: a9a881deef4d
Create Date: 2026-08-15 19:07:30.607271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23b83d33748'
down_revision: Union[str, Sequence[str], None] = 'a9a881deef4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_to_buy', 'units_to_buy',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=False)
    op.alter_column('shopping_item', 'units_bought',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=16, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_item', 'units_bought',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('item_to_buy', 'units_to_buy',
               existing_type=sa.DECIMAL(precision=16, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
