"""New models to manage ingredient units

Revision ID: d97c3758f282
Revises: 526339f10605
Create Date: 2026-06-16 18:17:31.728714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97c3758f282'
down_revision: Union[str, Sequence[str], None] = '526339f10605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_group',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_unit',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_unit_group_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_unit_group_id'], ['unit_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('ingredient', sa.Column('ref_ingredient_unit_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'ingredient', 'ingredient_unit', ['ref_ingredient_unit_id'], ['id'])
    # op.add_column('meal_ingredient', sa.Column('ingredient_unit', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('meal_ingredient', 'ingredient_unit')
    op.drop_constraint(None, 'ingredient', type_='foreignkey')
    op.drop_column('ingredient', 'ref_ingredient_unit_id')
    op.drop_table('ingredient_unit')
    op.drop_table('unit_group')
    # ### end Alembic commands ###
