"""Shopping models

Revision ID: ec1e781f23d5
Revises: 014ae6ed70d8
Create Date: 2026-07-17 23:23:01.861794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1e781f23d5'
down_revision: Union[str, Sequence[str], None] = '014ae6ed70d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopping',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shopping_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_household_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_item',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('ref_shopping_id', sa.String(length=64), nullable=False),
    sa.Column('ref_item_category_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ref_item_category_id'], ['item_category.id'], ),
    sa.ForeignKeyConstraint(['ref_shopping_id'], ['shopping.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_item')
    op.drop_table('shopping')
    op.drop_table('item_category')
    # ### end Alembic commands ###
