"""Add multiplier_to_base attribute to IngredientUnit

Revision ID: fe8f8c4507fb
Revises: 5f7cd46464c7
Create Date: 2026-06-16 19:27:14.998820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8f8c4507fb'
down_revision: Union[str, Sequence[str], None] = '5f7cd46464c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_unit', sa.Column('multiplier_to_base', sa.DECIMAL(precision=18, scale=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_unit', 'multiplier_to_base')
    # ### end Alembic commands ###
